import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import "./globals.css";

import Box from "@mui/material/Box";
import CssBaseline from "@mui/material/CssBaseline";
import Toolbar from "@mui/material/Toolbar";
import Typography from "@mui/material/Typography";

import Topbar from "./(component)/topbar/topbarIndex";
import Sidebar from "./(component)/sidebar/sidebarIndex";
import { ReduxProvider } from "@/redux/provider";

import { TopbarProvider } from "./(hooks)/topbarContext";
import { SidebarProvider } from "./(hooks)/sidebarContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <TopbarProvider>
            <SidebarProvider>
              <Box display={"flex"}>
                <CssBaseline />
                <Topbar />
                <Sidebar />
                <Box component="main" flexGrow={1} padding={3}>
                  <Toolbar />
                  {children}
                  <Typography paragraph>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed
                    do eiusmod tempor incididunt ut labore et dolore magna
                    aliqua. Rhoncus dolor purus non enim praesent elementum
                    facilisis leo vel. Risus at ultrices mi tempus imperdiet.
                    Semper risus in hendrerit gravida rutrum quisque non tellus.
                    Convallis convallis tellus id interdum velit laoreet id
                    donec ultrices. Odio morbi quis commodo odio aenean sed
                    adipiscing. Amet nisl suscipit adipiscing bibendum est
                    ultricies integer quis. Cursus euismod quis viverra nibh
                    cras. Metus vulputate eu scelerisque felis imperdiet proin
                    fermentum leo. Mauris commodo quis imperdiet massa
                    tincidunt. Cras tincidunt lobortis feugiat vivamus at augue.
                    At augue eget arcu dictum varius duis at consectetur lorem.
                    Velit sed ullamcorper morbi tincidunt. Lorem donec massa
                    sapien faucibus et molestie ac.
                  </Typography>
                </Box>
              </Box>
            </SidebarProvider>
          </TopbarProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
