import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Box from "@mui/material/Box";
import CssBaseline from "@mui/material/CssBaseline";
import Toolbar from "@mui/material/Toolbar";

import Topbar from "./(component)/topbar/topbarIndex";
import Sidebar from "./(component)/sidebar/sidebarIndex";
import { ReduxProvider } from "@/redux/provider";

import { TopbarProvider } from "./(hooks)/topbarContext";
import { SidebarProvider } from "./(hooks)/sidebarContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <TopbarProvider>
            <SidebarProvider>
              <Box display={"flex"}>
                <CssBaseline />
                <Topbar />
                <Sidebar />
                <Box component="main" flexGrow={1} padding={3}>
                  <Toolbar />
                  {children}
                </Box>
              </Box>
            </SidebarProvider>
          </TopbarProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
